# Generated by Django 5.1.3 on 2024-11-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_repository",
                    models.URLField(
                        help_text="Link to the repository where the un-compiled, human readable code and related code is located."
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="HEAD",
                        help_text="The version of the resource in the format of a Git commit ID or Git tag.",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
